name: flutter_debug_options_cli
description: Enables or disables Chrome extensions when running Flutter.
version: 1.0.2
repository: https://github.com/eggp/flutter_debug_options_cli

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  args: 2.4.2
  pub_update_checker: 1.2.0
  ansicolor: 2.0.1
  collection: 1.17.0
  dart_emoji: 0.2.0+2

dev_dependencies:
  lints: 2.1.1
  test: 1.24.3

executables:
  flutter_debug_options_cli: flutter_debug_options_cli